// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DetectEpi
Rcpp::List DetectEpi(SEXP inputfile_X, SEXP inputfile_Y, SEXP inputfile_COV);
RcppExport SEXP depi_DetectEpi(SEXP inputfile_XSEXP, SEXP inputfile_YSEXP, SEXP inputfile_COVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inputfile_X(inputfile_XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputfile_Y(inputfile_YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputfile_COV(inputfile_COVSEXP);
    rcpp_result_gen = Rcpp::wrap(DetectEpi(inputfile_X, inputfile_Y, inputfile_COV));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP depi_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// eigenK
Rcpp::List eigenK(SEXP inputFile);
RcppExport SEXP depi_eigenK(SEXP inputFileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inputFile(inputFileSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenK(inputFile));
    return rcpp_result_gen;
END_RCPP
}
