# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DetectEpi <- function(inputfile_X, inputfile_Y, inputfile_COV, MAX_ROW, MAX_COL, IS_EXIST_COV) {
    .Call('_depi_DetectEpi', PACKAGE = 'depi', inputfile_X, inputfile_Y, inputfile_COV, MAX_ROW, MAX_COL, IS_EXIST_COV)
}

rcpp_hello <- function() {
    .Call('_depi_rcpp_hello', PACKAGE = 'depi')
}

